require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PanlistsController do

  # This should return the minimal set of attributes required to create a valid
  # Panlist. As you add validations to Panlist, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PanlistsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all panlists as @panlists" do
      panlist = Panlist.create! valid_attributes
      get :index, {}, valid_session
      assigns(:panlists).should eq([panlist])
    end
  end

  describe "GET show" do
    it "assigns the requested panlist as @panlist" do
      panlist = Panlist.create! valid_attributes
      get :show, {:id => panlist.to_param}, valid_session
      assigns(:panlist).should eq(panlist)
    end
  end

  describe "GET new" do
    it "assigns a new panlist as @panlist" do
      get :new, {}, valid_session
      assigns(:panlist).should be_a_new(Panlist)
    end
  end

  describe "GET edit" do
    it "assigns the requested panlist as @panlist" do
      panlist = Panlist.create! valid_attributes
      get :edit, {:id => panlist.to_param}, valid_session
      assigns(:panlist).should eq(panlist)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Panlist" do
        expect {
          post :create, {:panlist => valid_attributes}, valid_session
        }.to change(Panlist, :count).by(1)
      end

      it "assigns a newly created panlist as @panlist" do
        post :create, {:panlist => valid_attributes}, valid_session
        assigns(:panlist).should be_a(Panlist)
        assigns(:panlist).should be_persisted
      end

      it "redirects to the created panlist" do
        post :create, {:panlist => valid_attributes}, valid_session
        response.should redirect_to(Panlist.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved panlist as @panlist" do
        # Trigger the behavior that occurs when invalid params are submitted
        Panlist.any_instance.stub(:save).and_return(false)
        post :create, {:panlist => { "name" => "invalid value" }}, valid_session
        assigns(:panlist).should be_a_new(Panlist)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Panlist.any_instance.stub(:save).and_return(false)
        post :create, {:panlist => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested panlist" do
        panlist = Panlist.create! valid_attributes
        # Assuming there are no other panlists in the database, this
        # specifies that the Panlist created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Panlist.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => panlist.to_param, :panlist => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested panlist as @panlist" do
        panlist = Panlist.create! valid_attributes
        put :update, {:id => panlist.to_param, :panlist => valid_attributes}, valid_session
        assigns(:panlist).should eq(panlist)
      end

      it "redirects to the panlist" do
        panlist = Panlist.create! valid_attributes
        put :update, {:id => panlist.to_param, :panlist => valid_attributes}, valid_session
        response.should redirect_to(panlist)
      end
    end

    describe "with invalid params" do
      it "assigns the panlist as @panlist" do
        panlist = Panlist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Panlist.any_instance.stub(:save).and_return(false)
        put :update, {:id => panlist.to_param, :panlist => { "name" => "invalid value" }}, valid_session
        assigns(:panlist).should eq(panlist)
      end

      it "re-renders the 'edit' template" do
        panlist = Panlist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Panlist.any_instance.stub(:save).and_return(false)
        put :update, {:id => panlist.to_param, :panlist => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested panlist" do
      panlist = Panlist.create! valid_attributes
      expect {
        delete :destroy, {:id => panlist.to_param}, valid_session
      }.to change(Panlist, :count).by(-1)
    end

    it "redirects to the panlists list" do
      panlist = Panlist.create! valid_attributes
      delete :destroy, {:id => panlist.to_param}, valid_session
      response.should redirect_to(panlists_url)
    end
  end

end
